kind = "mobile"
previewPath = "/"
title = "Peradi Hadir"
version = "1.0.0"
id = "artifacts/peradi-hadir"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24702

[services.development]
run = "pnpm --filter @workspace/peradi-hadir run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/peradi-hadir", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/peradi-hadir", "run", "serve" ]

[services.env]
PORT = "24702"
BASE_PATH = "/"
